In [4]:
import numpy as np

arr = np.array([0,1,2,3,4,5,6])

print(arr)
print("-" * 50)
print(arr.shape)

[0 1 2 3 4 5 6]
--------------------------------------------------
(7,)


In [5]:
arr_2D = np.array([  [1,2,3,4] , 
                     [5,6,7,8]  ])

print(arr_2D)
print("-" * 50)
print(arr_2D.shape)

[[1 2 3 4]
 [5 6 7 8]]
--------------------------------------------------
(2, 4)


In [6]:
arr_3D = np.array([ [[1,2,3],[4,5,6]] ,
                    [[7,8,9],[10,11,12]] ])

print(arr_3D)
print("-" * 50)
print(arr_3D.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
--------------------------------------------------
(2, 2, 3)


In [8]:
# Reshape per cambiare la forma di un array

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

arrReshaped = arr.reshape(3,4)
print(arr)
print("-" * 50)
print(arrReshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
--------------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

arrReshaped = arr.reshape(2,2,3)
print(arrReshaped)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
# Flattening, "appiattire" l'array

print(arrReshaped.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
