In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr[2:5])  #indice iniziale INCLUSO indice finale ESCLUSO

[3 4 5]


In [4]:
print(arr[1: ])

[2 3 4 5 6]


In [6]:
print(arr[1:-1])

[2 3 4 5]


In [7]:
arr1 = np.arange(0,11)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
print(arr1[0: 10 : 2]) # con un ulteriore ":2", salto di 2

[0 2 4 6 8]


In [11]:
arr_2D = np.array([  [1,2,3,4] , 
                     [5,6,7,8]  ])

print(arr_2D[1, 0:2])
print(arr_2D[0, 0:-1])

[5 6]
[1 2 3]


In [15]:
arr_3D = np.array([ [[1,2,3],[4,5,6]] ,
                    [[7,8,9],[10,11,12]] ])

print(arr_3D[0,1,1])
print(arr_3D[1,1,1])
print(arr_3D[0,1, :])

5
11
[4 5 6]
