In [2]:
import numpy as np

arr = np.arange (0, 10)
print(arr)

print("-" * 50)

arr_1 = np.array_split(arr, 3)
print(arr_1)

[0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [3]:
arr_s = np.array ([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12]])
print(arr_s)

print("-" * 50)

vs = np.array_split(arr_s, 3) # axis = 0
print(vs)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
--------------------------------------------------
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [5]:
vs = np.array_split(arr_s, 3, axis = 1)
print(vs) # suddivide prendendo come riferimento i numeri incolonnati

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64)]


In [6]:
# "hsplit" e "vsplit"

n_arr = np.array([  [1,2,3] , [4,5,6] , [7,8,9] , [10,11,12] , [13,14,15] , [16,17,18]  ])
print(n_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [7]:
n2 = np.vsplit(n_arr, 3) # uguale ad .array_split axis = 0
print(n2)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [8]:
n2 = np.hsplit(n_arr, 3) # uguale .array_split axis = 1
print(n2)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
