In [1]:
import numpy as np

In [2]:
# Creare array 1D

arr = np.array([0,1,2,3,4,5,6])
print(arr)

[0 1 2 3 4 5 6]


In [5]:
# Creare array 2D

arr_2D = np.array([  [1,2,3,4] , 
                     [5,6,7,8]  ])
print(arr_2D)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
# Creare array 3D

arr_3D = np.array([ [[1,2,3],[4,5,6]] ,
                    [[7,8,9],[10,11,12]] ])
print(arr_3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
# Mandare a schermo le dimensioni con "ndim"

print(arr.ndim)
print(arr_2D.ndim)
print(arr_3D.ndim)

1
2
3


In [9]:
# Creare array di qualsiasi dimensione con "ndmin"

arr_5D = np.array([1,2,3,4,5,6,7,8,9,10], ndmin = 5)
print(arr_5D)

[[[[[ 1  2  3  4  5  6  7  8  9 10]]]]]


In [11]:
# Arange, zeros e ones

arr = np.arange(0, 15)
print(arr)

# step by 5

arr1 = np.arange(0, 100, 5)
print(arr1)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [21]:
#Zeros

arr = np.zeros(3)
print(arr)

print("-" * 50)

arr1 = np.zeros((3,2))
print(arr1)

print("-" * 50)

arr1 = np.zeros((3,2,5))
print(arr1)

[0. 0. 0.]
--------------------------------------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]]
--------------------------------------------------
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [22]:
# Ones

arr = np.ones(3)
print(arr)

print("-" * 50)

arr1 = np.ones((3,2))
print(arr1)

print("-" * 50)

arr1 = np.ones((3,2,5))
print(arr1)

[1. 1. 1.]
--------------------------------------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]]
--------------------------------------------------
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
