In [4]:
import numpy as np

print(type(np.add)) # UFUNC , funzione universale
print(type(np.concatenate)) # funzione normale

<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


In [5]:
# Creare la propria UFUNC

arr = np.array([1,2,3,4,5,6])

def addCinque(x):
    return x + 5

# IMPORTANTE! Registrare funzione
addCinque = np.frompyfunc(addCinque, 1, 1) #nome funzione, n° argomenti input, n°output

print(addCinque(arr))

[6 7 8 9 10 11]


In [7]:
lista_numeri = ([1,2,3,4,5,6])
print(addCinque(lista_numeri))

# funziona anche su lista numeri perchè ho REGISTRATO precedentemente la funz
# quindi in automatico converte la lista in un array

[6 7 8 9 10 11]


In [8]:
# Altre funzioni universali

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 10, 15, 20, 25])

arr = np.add(arr1, arr2)
print(arr)

[15 30 45 60 75]


In [12]:
arr = np.subtract(arr1, arr2)
print(arr)

[ 5 10 15 20 25]


In [13]:
arr = np.multiply(arr1, arr2)
print(arr)

[  50  200  450  800 1250]


In [14]:
arr = np.divide(arr1, arr2)
print(arr)

[2. 2. 2. 2. 2.]


In [16]:
arr = np.remainder(arr1, arr2)  # resto
print(arr)

[0 0 0 0 0]


In [20]:
arr1 = np.array([3.145646636335, 6.77546454356, 8.949329392])
arrTrunc = np.trunc(arr1)
print(arrTrunc)

[3. 6. 8.]
