In [3]:
import numpy as np

# Concatenate 1D e 2D

arr1 = np.array ([1,2,3])
arr2 = np.array ([5,6,7])

arr_con = np.concatenate((arr1,arr2))
print(arr_con)

[1 2 3 5 6 7]


In [7]:
# 2D

arr1 = np.array ([[1,2] , [3,4]])
arr2 = np.array ([[5,6] , [7,8]])

arr_con = np.concatenate((arr1,arr2)) # axis = 0, così concatena verticalmente
print(arr_con)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
arr1 = np.array ([[1,2] , [3,4]])
arr2 = np.array ([[5,6] , [7,8]])

arr_con = np.concatenate((arr1,arr2), axis = 1) # concatena orizzontalmente
print(arr_con)

[[1 2 5 6]
 [3 4 7 8]]


In [14]:
# Stack, hstack e vstack

arr1 = np.array ([1,2,3])
arr2 = np.array ([5,6,7])

arr_con = np.concatenate((arr1,arr2))
print(arr_con)

print("-" * 50)

arr_stacked = np.stack ((arr1,arr2), axis = 0)
print(arr_stacked)

print("-" * 50)

arr_stacked_ax1 = np.stack ((arr1,arr2), axis = 1)
print(arr_stacked_ax1)

[1 2 3 5 6 7]
--------------------------------------------------
[[1 2 3]
 [5 6 7]]
--------------------------------------------------
[[1 5]
 [2 6]
 [3 7]]


In [10]:
# "hstack" unisce in orizzontale

arr_stacked = np.hstack ((arr1,arr2))
print(arr_stacked)

[1 2 3 5 6 7]


In [11]:
# "vstack" unisce in verticale

arr_stacked = np.vstack ((arr1,arr2))
print(arr_stacked)

[[1 2 3]
 [5 6 7]]
