In [6]:
import numpy as np

# Copy

arr = np.array([5,7,9,11,13])
arrCopy = arr.copy()

arr[0] = 10  #cambierà solo l'originale, la copia rimane uguale a prima

print(arr)
print(arrCopy)

[10  7  9 11 13]
[ 5  7  9 11 13]


In [7]:
# View

arr = np.array([5,7,9,11,13])
arrView = arr.view()

arr[0] = 10   #cambiano entrambi gli array, sostanziale differenza da "copy"

print(arr)
print(arrView)

[10  7  9 11 13]
[10  7  9 11 13]


In [9]:
# Check della proprietà dei dati

arr = np.array([5,7,9,11,13])
arrView = arr.view()

print(arr.base)
print(arrView.base)

None
[ 5  7  9 11 13]
