In [4]:
import numpy as np

# Cercare con "where", ritorna indici

arr = np.array([1,2,3,4,5,6,7,8])

arrIndex = np.where(arr == 7)
print(arrIndex)
arrIndex_pari = np.where(arr % 2 == 0)
print(arrIndex_pari)
arrIndex_dispari = np.where(arr % 2 == 1)
print(arrIndex_dispari)

#indica le posizioni interno all'array (1,3,5 ecc...)

(array([6]),)
(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)


In [6]:
# Ordinare un array disordinato con "sort"

arr = np.array([7, 11, 15, 2, 3, 6, 10, 1])
arrOrdinato = np.sort(arr)
print(arrOrdinato)

arr_stringa = (["Robbie" , "Paulie" , "Jasmin" , "Giga"])
arr_stringaOrdinato = np.sort(arr_stringa)
print(arr_stringaOrdinato)

[ 1  2  3  6  7 10 11 15]
['Giga' 'Jasmin' 'Paulie' 'Robbie']


In [10]:
# Ordinare array a più dimensioni

arr = ( [[7,4,2] , [19,3,9]] )
arrOrdinato = np.sort(arr)
print(arrOrdinato)

print("-" * 50) #divisore

arr_3D = ([ [[2,0,9],[7,3,8]] , [[22,1,90],[0,10,4]] ])
arr_3DOrdinato = np.sort(arr_3D)
print(arr_3DOrdinato)


[[ 2  4  7]
 [ 3  9 19]]
--------------------------------------------------
[[[ 0  2  9]
  [ 3  7  8]]

 [[ 1 22 90]
  [ 0  4 10]]]


In [11]:
# Filtrare con esempio statico, dinamico e scorciatoia

# Statico

arr = np.array([1,2,3,4,5,6])

filtroPari = [False, True, False, True, False, True]
arrayFiltrato = arr[filtroPari]
print(arrayFiltrato)

[2 4 6]


In [14]:
# Dinamico

arr = np.array([1,2,3,4,5,6])

filtro = []

for n in arr:
    if n % 2 == 0:
        filtro.append(True)
    else:
        filtro.append(False)

arrayFiltrato = arr[filtro]
print(arrayFiltrato)

[2 4 6]


In [15]:
# Scorciatoia

arr = np.array([1,2,3,4,5,6])

filtro = arr % 2 == 0

arrayFiltrato = arr[filtro]
print(arrayFiltrato)

[2 4 6]
