In [3]:
#Randint rand, generare  random array con randint e rand (1D e 2D)

import numpy as np
from numpy import random

numero = random.randint(100)
print(numero)

numero = random.rand() #numero compreso tra 0 e 1 
print(numero)

63
0.13917839653017716


In [7]:
# Creare array di una dimensione

arr = random.randint(100, size = 5)
print(arr)

print("-" * 50)  #divisiore

# Creare array di più dimensioni

arr_2D = random.randint(100, size = (5,6))
print(arr_2D)

print("-" * 50)  #divisiore

arr_3D = random.randint(100, size = (2,3,5))
print(arr_3D)


[48 96 90 62 13]
--------------------------------------------------
[[ 6 61 86 45 47 87]
 [68 80 70 18 89 53]
 [52 61 59 72 82 82]
 [33 81  0 99 87 37]
 [50 77 38 97 26 52]]
--------------------------------------------------
[[[16 70 74  8 55]
  [61 30  0 90 57]
  [ 3 61 82  1 96]]

 [[19 98 34 43 92]
  [70  0 61 47 19]
  [37 19 32 95 11]]]


In [11]:
# "Rand"

arr = random.rand(5) #size = 5
print(arr)

print("-" * 50)  #divisiore

# Creare array di più dimensioni

arr_2D = random.rand(5,6) #size = 5,6
print(arr_2D)

print("-" * 50)  #divisiore

arr_3D = random.rand(2,3,5)
print(arr_3D)

[0.70119864 0.36504829 0.31970683 0.13459367 0.66547589]
--------------------------------------------------
[[0.42973747 0.86045249 0.2262875  0.20947089 0.72266466 0.56887566]
 [0.02178309 0.51510698 0.39229226 0.60082475 0.80051861 0.1489391 ]
 [0.41088944 0.19305774 0.77047932 0.1505277  0.11326747 0.99666479]
 [0.04812363 0.70777382 0.13499101 0.51290575 0.97293597 0.22873765]
 [0.67099654 0.18751445 0.91297229 0.08033825 0.7052679  0.96624394]]
--------------------------------------------------
[[[0.85554242 0.51397643 0.43049299 0.21812135 0.37884333]
  [0.91878279 0.13512711 0.88805735 0.52871    0.81624965]
  [0.80046611 0.50221992 0.80046039 0.17638087 0.6871211 ]]

 [[0.58171949 0.29857122 0.73207297 0.02173678 0.48542701]
  [0.61884143 0.49499188 0.03733414 0.76778402 0.74663077]
  [0.38634477 0.95024375 0.79920127 0.83302462 0.24780947]]]


In [16]:
# Choice per estrarre valore e generare array

arr = np.array([1,2,3,4,5,6,7,8,9,10])
arrChoice = np.random.choice(arr)
print(arrChoice)

4


In [18]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arrChoice = np.random.choice(arr, size = (5))
print(arrChoice)

[ 4  1  5 10 10]


In [20]:
# Data distribution con probabilità

values = np.array([10,20,30,40,50])
probability = ([0.1, 0.2, 0.2, 0.2, 0.3])
arrChoice = np.random.choice(values, p = probability, size = (20))
print(arrChoice)

[20 30 40 50 50 30 40 40 10 40 20 50 40 20 40 40 20 20 20 20]


In [21]:
values = np.array([10,20,30,40,50])
probability = ([1, 0, 0, 0, 0])
arrChoice = np.random.choice(values, p = probability, size = (20))
print(arrChoice)

[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]


In [27]:
# Shuffle (agisce su array) e permutation (ritorna nuovo array)


arr = np.array([1,2,3,4,5,6,7,8,9,10])
arrShufflato = random.shuffle(arr)
print(arrShufflato)

None


In [28]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arrPermutato = random.permutation(arr)
print(arrPermutato)

[ 9  3 10  4  6  2  5  8  1  7]
